baseURL = "https://clearstar.blackit.hu/"
title = "ClearStar"
defaultContentLanguage = "hu"
defaultContentLanguageInSubdir = false
disableKinds = ["taxonomy", "term", "section", "rss"]
enableRobotsTXT = true

[params]
  store = "https://apps.microsoft.com/store/detail/9N193WDBH7KF?cid=DevShareMCLPCS"
  github = "https://github.com/Fekete85/ClearStar"
  privacy = "https://github.com/Fekete85/ClearStar/blob/main/PRIVACY.md"
  support = "https://revolut.me/laszlohmy"

[languages.hu]
  languageName = "HU"
  languageCode = "hu"
  weight = 1

[languages.en]
  languageName = "EN"
  languageCode = "en"
  weight = 2
